name       : libmateweather
version    : 1.14.3
release    : 2
source     :
    - http://pub.mate-desktop.org/releases/1.14/libmateweather-1.14.3.tar.xz : 21507911543bccdaec57541b030de0d5522ef9640b1ac24044223bb43d026266
license    : GPL-2.1
component  : desktop.mate
summary    : MATE weather access library
description: |
    libmateweather is a library to access weather information from online services for numerous locations.
builddeps  :
    - pkgconfig(libsoup-2.4)
    - pkgconfig(pygobject-2.0)
    - pkgconfig(gtk+-3.0)
setup      : |
    %configure --disable-static --with-gtk=3.0
build      : |
    %make
install    : |
    %make_install
