name       : libmateweather
version    : 1.16.1
release    : 4
source     :
    - http://pub.mate-desktop.org/releases/1.16/libmateweather-1.16.1.tar.xz : a3569ea5a51ec75eb29aadfba253faf04fbd3815d0a7882ddf6bd6c9c2422b70
license    : GPL-2.1
component  : desktop.mate
summary    : MATE weather access library
description: |
    libmateweather is a library to access weather information from online services for numerous locations.
builddeps  :
    - pkgconfig(libsoup-2.4)
    - pkgconfig(pygobject-2.0)
    - pkgconfig(gtk+-3.0)
setup      : |
    %configure --disable-static --with-gtk=3.0
build      : |
    %make
install    : |
    %make_install
