name       : libmateweather
version    : 1.22.1
release    : 16
source     :
    - https://github.com/mate-desktop/libmateweather/archive/v1.22.1.tar.gz : 554305ecac8edca85824a2ce64cac4dd2ba7f7dfd490ef2dd7b2a79e663d4654
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.mate
summary    : MATE weather access library
description: |
    libmateweather is a library to access weather information from online services for numerous locations.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtk-doc)
    - pkgconfig(libsoup-2.4)
    - mate-common
setup      : |
    %autogen --disable-static --enable-gtk-doc
build      : |
    %make
install    : |
    %make_install
