name       : libmateweather
version    : 1.20.0
release    : 9
source     :
    - https://pub.mate-desktop.org/releases/1.20/libmateweather-1.20.0.tar.xz : 076eddad046454d8e8f90413b1b33594975fc2a51c2a0cec1fff40b09adf15b1
license    : GPL-2.1
component  : desktop.mate
summary    : MATE weather access library
description: |
    libmateweather is a library to access weather information from online services for numerous locations.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(pygobject-2.0)
setup      : |
    %configure --disable-static --with-gtk=3.0
build      : |
    %make
install    : |
    %make_install
