name       : libmateweather
version    : 1.22.0
release    : 14
source     :
    - https://github.com/mate-desktop/libmateweather/archive/v1.22.0.tar.gz : 3b53bc0564f06d75e92331a7fb460eb5e8e6f0b7a5587840c89cc1d49238e55f
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.mate
summary    : MATE weather access library
description: |
    libmateweather is a library to access weather information from online services for numerous locations.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtk-doc)
    - pkgconfig(libsoup-2.4)
    - mate-common
setup      : |
    %autogen --disable-static --enable-gtk-doc
build      : |
    %make
install    : |
    %make_install
