name       : libmateweather
version    : 1.26.0
release    : 22
source     :
    - https://github.com/mate-desktop/libmateweather/releases/download/v1.26.0/libmateweather-1.26.0.tar.xz : a7fd9713099c88826fb67249771cd0cdb92ee9d4784068b1a165840b84607b15
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.mate
summary    : MATE weather access library
description: |
    libmateweather is a library to access weather information from online services for numerous locations.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtk-doc)
    - pkgconfig(libsoup-2.4)
setup      : |
    %configure --disable-static --enable-gtk-doc
build      : |
    %make
install    : |
    %make_install
