name       : libmateweather
version    : 1.16.0
release    : 3
source     :
    - http://pub.mate-desktop.org/releases/1.16/libmateweather-1.16.0.tar.xz : b3ed351e7f5d922444de28a05546cf7032cec3ea6d5c5cbb1ca1fc1e1e1c6be5
license    : GPL-2.1
component  : desktop.mate
summary    : MATE weather access library
description: |
    libmateweather is a library to access weather information from online services for numerous locations.
builddeps  :
    - pkgconfig(libsoup-2.4)
    - pkgconfig(pygobject-2.0)
    - pkgconfig(gtk+-3.0)
setup      : |
    %configure --disable-static --with-gtk=3.0
build      : |
    %make
install    : |
    %make_install
