name       : libmateweather
version    : 1.18.1
release    : 7
source     :
    - https://pub.mate-desktop.org/releases/1.18/libmateweather-1.18.1.tar.xz : 6af4ca73df3d0589481e74f8be843130359ba071d76195b3c4396d270874db7c
license    : GPL-2.1
component  : desktop.mate
summary    : MATE weather access library
description: |
    libmateweather is a library to access weather information from online services for numerous locations.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(pygobject-2.0)
setup      : |
    %configure --disable-static --with-gtk=3.0
build      : |
    %make
install    : |
    %make_install
