name       : libmateweather
version    : 1.18.0
release    : 5
source     :
    - https://pub.mate-desktop.org/releases/1.18/libmateweather-1.18.0.tar.xz : 72e205f92bd9aed1a1d82abb17c5e26d447198d8bbdccf969d50c1c7c429b287
license    : GPL-2.1
component  : desktop.mate
summary    : MATE weather access library
description: |
    libmateweather is a library to access weather information from online services for numerous locations.
builddeps  :
    - pkgconfig(libsoup-2.4)
    - pkgconfig(pygobject-2.0)
    - pkgconfig(gtk+-3.0)
setup      : |
    %configure --disable-static --with-gtk=3.0
build      : |
    %make
install    : |
    %make_install
