name       : libmateweather
version    : 1.24.0
release    : 18
source     :
    - https://github.com/mate-desktop/libmateweather/archive/v1.24.0.tar.gz : e82afbfbe62a1b1d25255c3c49e2bccb12e4e038638738c1ec607687fde3a59d
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.mate
summary    : MATE weather access library
description: |
    libmateweather is a library to access weather information from online services for numerous locations.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtk-doc)
    - pkgconfig(libsoup-2.4)
    - mate-common
setup      : |
    %autogen --disable-static --enable-gtk-doc
build      : |
    %make
install    : |
    %make_install
