name       : libmateweather
version    : 1.24.1
release    : 19
source     :
    - https://github.com/mate-desktop/libmateweather/archive/v1.24.1.tar.gz : 0048b727dd72e7c5564d8d5860089869efae446eb526766c070f33b4ab0115b2
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.mate
summary    : MATE weather access library
description: |
    libmateweather is a library to access weather information from online services for numerous locations.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtk-doc)
    - pkgconfig(libsoup-2.4)
    - mate-common
setup      : |
    %autogen --disable-static --enable-gtk-doc
build      : |
    %make
install    : |
    %make_install
