name       : libmateweather
version    : 1.20.1
release    : 11
source     :
    - https://pub.mate-desktop.org/releases/1.20/libmateweather-1.20.1.tar.xz : 21f35e05bb586c1a01b9754ad48726470ab456778350de32b6c5bdb286b5e12e
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.mate
summary    : MATE weather access library
description: |
    libmateweather is a library to access weather information from online services for numerous locations.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(pygobject-2.0)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
